# Generated by Django 3.2.25 on 2025-01-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('study_work', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('passport', models.CharField(max_length=11, unique=True)),
                ('given', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
