# Generated by Django 3.2.25 on 2025-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250208_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_book',
            field=models.FileField(blank=True, null=True, upload_to='book/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
