# Generated by Django 5.1.6 on 2025-02-13 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата взятия')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books_book', to='main.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взятая книга',
                'verbose_name_plural': 'Взятые книги',
            },
        ),
    ]
